export const SITE_URL = "https://venomid.network/"
export const SITE_TITLE = "Venom ID"
export const SITE_DESCRIPTION = "Your entire virtual identity in the blockchain in one simple link"
export const SITE_FULL_DESCRIPTION = "With VenomID, you can assign human-readable names to your blockchain and non-blockchain resources like Venom, BTC and ETH addresses, Links and more"
export const SITE_MANAGE_URL = "https://venomid.tools/"
export const SITE_PROFILE_URL = "https://venomid.link/"
export const VENOMSCAN_NFT = "https://testnet.venomscan.com/accounts/"
export const BTCSCAN_ADDRESS = "https://blockchair.com/bitcoin/"
export const ETHERSCAN_ADDRESS = "https://etherscan.io/address/"
//export const CONTRACT_ADDRESS = "0:247682756b04b9e2290fd1801bcd7cd9ab5e46a167ff339e3e176355b5db4901";
export const CONTRACT_ADDRESS = "0:2787ba200fd3e45c1a4854768f69310fe4e9566383761f27936aff61ad79c8ab";
export const SOCIAL_TWITTER = "venomid_network"
export const VID_MEDIUM_URL = "https://medium.com/@venomidapp";
export const VID_TELEGRAM_URL = "https://t.me/venomid_network";
export const VID_GITHUB_URL = "https://github.com/sam-shariat/venomid";
export const TWITTER_URL = "https://twitter.com/"
export const ZEALY_URL = "https://zealy.io/c/venomid/"
export const NFT_IMAGE_URL = "https://ipfs.io/ipfs/QmUvfedgHDXdiMsq5nfLPGLQrR4QAYXHzR5SETBZQ6RGyd";