import type { NextPage } from 'next';
import Head from 'next/head';
import ClaimSection from 'components/sections/ClaimSection';
import ManageSection from 'components/sections/ManageSection';
import ProfileSection from 'components/sections/ProfileSection';
import RoadmapSection from 'components/sections/RoadmapSection';
import AboutSection from 'components/sections/AboutSection';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Venom ID | Your entire virtual identity in the blockchain in one simple link</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos/vidicon.svg" />
      </Head>

      <ClaimSection />
      <ManageSection />
      <ProfileSection />
      <RoadmapSection />
      <AboutSection />
    </>
  );
};

export default Home;
