import type { NextPage } from 'next';
import Head from 'next/head';
import {
  Button,
  Container,
  Heading,
  Text,
  InputGroup,
  Input,
  InputLeftAddon,
  Stack,
  SimpleGrid,
  Box,
  Center,
} from '@chakra-ui/react';
import { useTranslate } from 'core/lib/hooks/use-translate';
import Venom from 'components/Venom';
import IphoneMockup from 'components/Mockup/venomid.link';
import { useMediaQuery } from '@chakra-ui/react';

const RoadMap: NextPage = () => {
  const { t } = useTranslate();
  const [notMobile] = useMediaQuery('(min-width: 800px)');
  return (
    <>
      <Head>
        <title>Venom ID | Your entire virtual identity in the blockchain in one simple link</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos/vidicon.svg" />
      </Head>

      <Container
        as="main"
        maxW="container.md"
        display="grid"
        placeContent="center"
        placeItems="center"
        minH="75vh">
        <>
          <SimpleGrid columns={[1, 2]} spacing="32px" my={notMobile ? 10 : 4}>
          <Center display="flex" flexDirection="column">
              <Venom />
            </Center>
            <Box display="flex" flexDirection="column" justifyContent="center">
              <Heading fontWeight="bold" fontSize="6xl">
                {t('title')}
              </Heading>
              <Text fontWeight="bold" fontSize={notMobile ? '4xl' : '2xl'} my={notMobile ? 10 : 4}>
                {t('description')}
              </Text>
            </Box>
          </SimpleGrid>
          <Text fontWeight="bold" fontSize={notMobile ? 'xl' : 'xl'} my={notMobile ? 10 : 4}>
            {t('claimDescription')}
          </Text> 
          <Stack direction={['column', 'row']} py={notMobile ? 10 : 4}>
            <InputGroup size="lg">
              <InputLeftAddon children="venomid.link/" />
              <Input placeholder="samy" />
            </InputGroup>
            <Button backgroundColor="var(--venom2)" size="lg" minWidth="300px">
              {t('claimButton')}
            </Button>
          </Stack>
        </>
      </Container>

      {/* ---------------------Management------------------------ */}
      <Box backgroundColor={"blackAlpha.300"}>
      <Container
        as="main"
        maxW="container.md"
        display="grid"
        placeContent="center"
        placeItems="center"
        minH="75vh">
        <>
          <SimpleGrid columns={[1, 2]} spacing="32px" my={10}>
            <Center display="flex" flexDirection="column">
              <IphoneMockup />
            </Center>
            <Center display="flex" flexDirection="column">
              <Heading fontWeight="bold" fontSize="5xl">
                {t('manage')}
              </Heading>
              <Text fontWeight="bold" fontSize={notMobile ? '3xl' : '2xl'} my={10}>
                {t('manageDescription')}
              </Text>
            </Center>
          </SimpleGrid>
          <Text fontSize={notMobile ? '3xl' : '2xl'} my={notMobile ? 10 : 0}>
            {t('dappDescription')}
          </Text>
          <Stack direction={['column', 'row']} my={10}>
            
            <Button backgroundColor="var(--purple2)" size="lg" minWidth="300px">
              {t('manageWebsiteButton')}
            </Button>
          </Stack>
        </>
      </Container>
      </Box>

    </>
  );
};

export default RoadMap;
